name: build-docker

on: 
  push:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code source
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Lister les fichiers présents
      - name: List Files in Repository
        run: ls -la

      # 3. Connexion à DockerHub (nécessite secrets pour DOCKER_USERNAME et DOCKER_PASSWORD)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build de l'image Docker
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # 5. Lister les images Docker locales
      - name: List Docker Images
        run: docker images

      # 6. Push de l'image vers DockerHub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
